@server=http://localhost:4004
@username=alice
@password=


### Product
# @name Product_GET
GET {{server}}/odata/v4/productshop/Product
Authorization: Basic {{username}}:{{password}}


### Product
# @name Product_POST
POST {{server}}/odata/v4/productshop/Product
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "Id": 2003771,
  "name": "name-2003771",
  "stock": 1,
  "price": 86,
  "category": "category-2003771"
}


### Product
# @name Product_PATCH
PATCH {{server}}/odata/v4/productshop/Product/2003771
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "Id": 2003771,
  "name": "name-2003771",
  "stock": 1,
  "price": 86,
  "category": "category-2003771"
}


### Product
# @name Product_DELETE
DELETE {{server}}/odata/v4/productshop/Product/2003771
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Suppiler
# @name Suppiler_GET
GET {{server}}/odata/v4/productshop/Suppiler
Authorization: Basic {{username}}:{{password}}


### Suppiler
# @name Suppiler_POST
POST {{server}}/odata/v4/productshop/Suppiler
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "1846322b-b39d-4621-9081-fcad5783bc68",
  "name": "name-1846322",
  "city": "city-1846322",
  "phone": 68
}


### Suppiler
# @name Suppiler_PATCH
PATCH {{server}}/odata/v4/productshop/Suppiler/1846322b-b39d-4621-9081-fcad5783bc68
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "1846322b-b39d-4621-9081-fcad5783bc68",
  "name": "name-1846322",
  "city": "city-1846322",
  "phone": 68
}


### Suppiler
# @name Suppiler_DELETE
DELETE {{server}}/odata/v4/productshop/Suppiler/1846322b-b39d-4621-9081-fcad5783bc68
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
